spring:
  application:
    name: VAN-service

server:
  port: 7070
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    com.card.payment: DEBUG

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha